name: astrology
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  auto_route: ^9.2.2
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_gen: ^5.8.0
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.2.1
  fzregex: ^2.0.0
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  jwt_decoder: ^2.0.1
  logger: ^2.4.0
  lottie: ^3.1.3
  provider: ^6.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/json/
